# ===----------------------------------------------------------------------=== #
#
# This file is Modular Inc proprietary.
#
# ===----------------------------------------------------------------------=== #
# REQUIRES: nvptx_backend
# RUN: %mojo -debug-level full %s | FileCheck %s

from gpu.muda import compile_nvptx_asm


@export("kernel")
fn kernel(x: Int) -> Int:
    return x


fn main():
    # CHECK: Generated by LLVM NVPTX Back-End
    # CHECK: .visible .entry kernel
    let asm = compile_nvptx_asm[fn (Int) -> Int, kernel]()
    print(asm)
