# generated by datamodel-codegen:
#   filename:  kserve.yaml
#   timestamp: 2024-08-15T22:19:28+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, RootModel


class MetadataServerResponse(BaseModel):
    name: str
    version: str
    extensions: list[str]


class MetadataServerErrorResponse(BaseModel):
    error: str


class MetadataTensor(BaseModel):
    name: str
    datatype: str
    shape: list[int]


class MetadataModelErrorResponse(BaseModel):
    error: str


class Parameters(BaseModel):
    pass


class TensorData(RootModel[list]):
    root: list = Field(..., title="tensor_data")


class RequestOutput(BaseModel):
    name: str
    parameters: Optional[Parameters] = None


class ResponseOutput(BaseModel):
    name: str
    shape: list[int]
    datatype: str
    parameters: Optional[Parameters] = None
    data: TensorData


class InferenceResponse(BaseModel):
    model_name: str
    model_version: Optional[str] = None
    id: Optional[str] = None
    parameters: Optional[Parameters] = None
    outputs: list[ResponseOutput]


class InferenceErrorResponse(BaseModel):
    error: Optional[str] = None


class MetadataModelResponse(BaseModel):
    name: str
    versions: Optional[list[str]] = None
    platform: str
    inputs: Optional[list[MetadataTensor]] = None
    outputs: Optional[list[MetadataTensor]] = None


class RequestInput(BaseModel):
    name: str
    shape: list[int]
    datatype: str
    parameters: Optional[Parameters] = None
    data: TensorData


class InferenceRequest(BaseModel):
    id: Optional[str] = None
    parameters: Optional[Parameters] = None
    inputs: list[RequestInput]
    outputs: Optional[list[RequestOutput]] = None
