# ===----------------------------------------------------------------------=== #
# Copyright (c) 2025, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

from sys.ffi import c_int, external_call
from sys.info import CompilationTarget


def get_errno() -> Int:
    """Get the current libc errno.

    Returns:
        The current libc errno.
    """

    @parameter
    if CompilationTarget.is_macos():
        return Int(external_call["__error", UnsafePointer[c_int]]()[])
    else:
        return Int(external_call["__errno_location", UnsafePointer[c_int]]()[])


def get_errno_message(var errno: Int = -1) -> String:
    """Get the error message for the given libc errno.

    Args:
        errno: The libc errno to get the error message for. If not provided,
            the current errno will be used.

    Returns:
        The error message for the given libc errno.
    """
    if errno == -1:
        errno = get_errno()

    @parameter
    if CompilationTarget.is_linux():
        alias errors = {
            1: "operation not permitted",
            2: "no such file or directory",
            3: "no such process",
            4: "interrupted system call",
            5: "input/output error",
            6: "no such device or address",
            7: "argument list too long",
            8: "exec format error",
            9: "bad file descriptor",
            10: "no child processes",
            11: "resource temporarily unavailable",
            12: "out of memory",
            13: "permission denied",
            14: "bad address",
            15: "block device required",
            16: "device or resource busy",
            17: "file exists",
            18: "invalid cross-device link",
            19: "no such device",
            20: "not a directory",
            21: "is a directory",
            22: "invalid argument",
            23: "file table overflow",
            24: "too many open files",
            25: "not a typewriter",
            26: "text file busy",
            27: "file too large",
            28: "no space left on device",
            29: "illegal seek",
            30: "read-only file system",
            31: "too many links",
            32: "broken pipe",
            33: "math argument out of domain",
            34: "result too large",
            35: "resource deadlock avoided",
            36: "file name too long",
            37: "no record locks available",
            38: "function not implemented",
            39: "directory not empty",
            40: "too many symbolic links encountered",
            42: "no message of desired type",
            43: "identifier removed",
            44: "channel number out of range",
            45: "level 2 not synchronized",
            46: "level 3 halted",
            47: "level 3 reset",
            48: "link number out of range",
            49: "protocol driver not attached",
            50: "no CSI structure available",
            51: "level 2 halted",
            52: "invalid exchange",
            53: "invalid request descriptor",
            54: "exchange full",
            55: "no anode",
            56: "invalid request code",
            57: "invalid slot",
            59: "bad font file format",
            60: "device not a stream",
            61: "no data available",
            62: "timer expired",
            63: "out of streams resources",
            64: "machine is not on the network",
            65: "package not installed",
            66: "object is remote",
            67: "link has been severed",
            68: "advertise error",
            69: "srmount error",
            70: "communication error on send",
            71: "protocol error",
            72: "multihop attempted",
            73: "RFS specific error",
            74: "bad message",
            75: "value too large for defined data type",
            76: "name not unique on network",
            77: "file descriptor in bad state",
            78: "remote address changed",
            79: "can not access a needed shared library",
            80: "accessing a corrupted shared library",
            81: ".lib section in a.out corrupted",
            82: "attempting to link in too many shared libraries",
            83: "cannot exec a shared library directly",
            84: "illegal byte sequence",
            85: "interrupted system call should be restarted",
            86: "streams pipe error",
            87: "too many users",
            88: "socket operation on non-socket",
            89: "destination address required",
            90: "message too long",
            91: "protocol wrong type for socket",
            92: "protocol not available",
            93: "protocol not supported",
            94: "socket type not supported",
            95: "operation not supported",
            96: "protocol family not supported",
            97: "address family not supported",
            98: "address already in use",
            99: "cannot assign requested address",
            100: "network is down",
            101: "network is unreachable",
            102: "network dropped connection on reset",
            103: "software caused connection abort",
            104: "connection reset by peer",
            105: "no buffer space available",
            106: "transport endpoint is already connected",
            107: "transport endpoint is not connected",
            108: "cannot send after transport endpoint shutdown",
            109: "too many references",
            110: "connection timed out",
            111: "connection refused",
            112: "host is down",
            113: "no route to host",
            114: "operation already in progress",
            115: "operation now in progress",
            116: "stale file handle",
            117: "structure needs cleaning",
            118: "not a XENIX named type file",
            119: "no XENIX semaphores available",
            120: "is a named type file",
            121: "remote I/O error",
            122: "disk quota exceeded",
            123: "no medium found",
            124: "wrong medium type",
            125: "operation canceled",
            126: "required key not available",
            127: "key has expired",
            128: "key has been revoked",
            129: "key was rejected by service",
            130: "owner died",
            131: "state not recoverable",
            132: "operation not possible due to RF-kill",
            133: "memory page has hardware error",
        }
        if errno <= 133:
            return errors[errno]

    elif CompilationTarget.is_macos():
        alias errors = {
            1: "operation not permitted",
            2: "no such file or directory",
            3: "no such process",
            4: "interrupted system call",
            5: "input/output error",
            6: "no such device or address",
            7: "argument list too long",
            8: "exec format error",
            9: "bad file descriptor",
            10: "no child processes",
            11: "resource deadlock avoided (differs from Linux)",
            12: "out of memory",
            13: "permission denied",
            14: "bad address",
            15: "block device required",
            16: "device or resource busy",
            17: "file exists",
            18: "invalid cross-device link",
            19: "no such device",
            20: "not a directory",
            21: "is a directory",
            22: "invalid argument",
            23: "file table overflow",
            24: "too many open files",
            25: "not a typewriter",
            26: "text file busy",
            27: "file too large",
            28: "no space left on device",
            29: "illegal seek",
            30: "read-only file system",
            31: "too many links",
            32: "broken pipe",
            33: "math argument out of domain",
            34: "result too large",
            35: "no message of desired type",
            36: "identifier removed",
            37: "illegal byte sequence",
            38: "value too large for defined data type",
            39: "operation canceled",
            45: "operation not supported (differs from Linux EOPNOTSUPP)",
            46: "bad message",
            47: "no data available",
            48: "out of streams resources",
            49: "device not a stream",
            50: "timer expired",
            51: "machine is not on the network",
            52: "package not installed",
            53: "object is remote",
            54: "link has been severed",
            55: "advertise error",
            56: "srmount error",
            57: "communication error on send",
            58: "protocol error",
            59: "multihop attempted",
            60: "RFS specific error",
            61: "directory not empty",
            62: "file name too long",
            63: "too many symbolic links",
            64: "operation not supported on socket",
            65: "protocol family not supported",
            66: "connection reset by peer",
            67: "no buffer space available",
            68: "address family not supported",
            69: "protocol wrong type for socket",
            70: "socket operation on non-socket",
            71: "protocol not available",
            72: "cannot send after transport endpoint shutdown",
            73: "connection refused",
            74: "address already in use",
            75: "software caused connection abort",
            76: "network is unreachable",
            77: "network is down",
            78: "connection timed out",
            79: "host is down",
            80: "no route to host",
            81: "operation now in progress",
            82: "operation already in progress",
            83: "destination address required",
            84: "message too long",
            85: "protocol not supported",
            86: "socket type not supported",
            87: "cannot assign requested address",
            88: "network dropped connection on reset",
            89: "transport endpoint is already connected",
            90: "transport endpoint is not connected",
            91: "too many references",
            94: "too many users",
            95: "disk quota exceeded",
            96: "stale file handle",
            97: "not a XENIX named type file",
            98: "is a named type file",
            99: "remote I/O error",
            100: "no medium found",
            101: "wrong medium type",
            102: "required key not available",
            103: "key has expired",
            104: "key has been revoked",
            105: "key was rejected by service",
        }
        if errno <= 133:
            return errors[errno]
    return String("unknown libc errno (", errno, ")")
