# ===----------------------------------------------------------------------=== #
#
# This file is Modular Inc proprietary.
#
# ===----------------------------------------------------------------------=== #
# RUN: %mojo-no-debug %s | FileCheck %s

from sys._assembly import inlined_assembly
from memory import UnsafePointer
from pathlib import Path

from gpu import ThreadIdx
from gpu.host import DeviceContext
from gpu.host._compile import _compile_code_asm


fn kernel(x: Int) -> Int:
    return ThreadIdx.x()


fn parametric[f: fn (Int) -> Int]() -> Int:
    return f(42)


# CHECK-LABEL: test_compile_code
def test_compile_code():
    print("== test_compile_code")

    # CHECK: Generated by LLVM NVPTX Back-End
    # CHECK: .visible .entry  test_compile_nvptx_kernel_
    print(_compile_code_asm[kernel]())
    # CHECK: Generated by LLVM NVPTX Back-End
    # CHECK: .visible .entry test_compile_nvptx_parametric_
    print(_compile_code_asm[parametric[kernel]]())
    # CHECK: ; ModuleID =
    # CHECK: lvm.nvvm.read.ptx.sreg.tid.x()
    print(_compile_code_asm[parametric[kernel], emission_kind="llvm"]())


# CHECK-LABEL: test_compile_function
def test_compile_function():
    print("== test_compile_function")

    fn kernel(x: UnsafePointer[Int]):
        x[0] = ThreadIdx.x()

    # CHECK: tid.x

    with DeviceContext() as ctx:
        _ = ctx.compile_function[kernel, dump_ptx=True]()


fn kernel_inlined_assembly():
    inlined_assembly["nanosleep.u32 $0;", NoneType, constraints="r"](
        UInt32(100)
    )


# CHECK-LABEL: test_compile_function_with_assembly
def test_compile_function_with_assembly():
    print("== test_compile_function_with_assembly")

    # CHECK: nanosleep
    # CHECK-NOT: begin assembly

    with DeviceContext() as ctx:
        _ = ctx.compile_function[kernel_inlined_assembly, dump_ptx=True]()


# CHECK-LABEL: test_compile_function_with_path
def test_compile_function_with_path():
    print("== test_compile_function_with_path")

    # CHECK: nanosleep
    # CHECK-NOT: begin assembly

    with DeviceContext() as ctx:
        alias out_file = Path("/tmp/my_file.ptx")
        _ = ctx.compile_function[kernel_inlined_assembly, dump_ptx=out_file]()
        print(out_file.read_text())


# CHECK-LABEL: test_compile_function_with_path_func
def test_compile_function_with_path_func():
    print("== test_compile_function_with_path_func")

    # CHECK: nanosleep
    # CHECK-NOT: begin assembly

    with DeviceContext() as ctx:
        var out_file_name = "my_file_2.ptx"
        alias out_dir = Path("/tmp")

        @parameter
        fn dummy_fn() capturing -> Path:
            return out_dir / out_file_name

        _ = ctx.compile_function[kernel_inlined_assembly, dump_ptx=dummy_fn]()

        var out_file = out_dir / out_file_name
        print(out_file.read_text())


def main():
    test_compile_code()
    test_compile_function()
    test_compile_function_with_assembly()
    test_compile_function_with_path()
    test_compile_function_with_path_func()
