# ===----------------------------------------------------------------------=== #
#
# This file is Modular Inc proprietary.
#
# ===----------------------------------------------------------------------=== #
# REQUIRES: nvptx_backend
# RUN: %mojo -debug-level full %s | FileCheck %s

from sys.info import triple_is_nvidia_cuda
from gpu import ThreadIdx
from gpu.nvidia_host import _compile_nvptx_asm


@export("kernel")
fn kernel(x: Int) -> Int:
    @parameter
    if triple_is_nvidia_cuda():
        return ThreadIdx.x()
    else:
        return 0


fn main():
    # CHECK: Generated by LLVM NVPTX Back-End
    # CHECK: .visible .entry kernel
    let asm = _compile_nvptx_asm[fn (Int) -> Int, kernel]()
    print(asm)
