# ===----------------------------------------------------------------------=== #
#
# This file is Modular Inc proprietary.
#
# ===----------------------------------------------------------------------=== #
#
# GENERATED FILE, DO NOT EDIT!
#
# Last generated by stef at 2024-01-12 08:19:31.252951 with command
# ```
#   ./utils/mojo-mlir/generate_mlir_c_bindings.sh \
#     BuiltinTypes.h
# ```
#
# ===----------------------------------------------------------------------=== #

from .AffineMap import MlirAffineMap
from .ffi import MLIR_func
from .IR import MlirAttribute, MlirContext, MlirLocation, MlirType
from .Support import MlirStringRef, MlirTypeID

# ===-- mlir-c/BuiltinTypes.h - C API for MLIR Builtin types ------*- C -*-===//
#
#  Part of the LLVM Project, under the Apache License v2.0 with LLVM
#  Exceptions.
#  See https://llvm.org/LICENSE.txt for license information.
#  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# ===----------------------------------------------------------------------===//


# ===----------------------------------------------------------------------===//
#  Integer types.
# ===----------------------------------------------------------------------===//


fn mlirIntegerTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Integer type."""
    return MLIR_func["mlirIntegerTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAInteger(type: MlirType) -> Bool:
    """Checks whether the given type is an integer type."""
    return MLIR_func["mlirTypeIsAInteger", fn (MlirType) -> Bool]()(type)


fn mlirIntegerTypeGet(ctx: MlirContext, bitwidth: Int16) -> MlirType:
    """Creates a signless integer type of the given bitwidth in the context. The
    type is owned by the context."""
    return MLIR_func[
        "mlirIntegerTypeGet", fn (MlirContext, Int16) -> MlirType
    ]()(ctx, bitwidth)


fn mlirIntegerTypeSignedGet(ctx: MlirContext, bitwidth: Int16) -> MlirType:
    """Creates a signed integer type of the given bitwidth in the context. The type
    is owned by the context."""
    return MLIR_func[
        "mlirIntegerTypeSignedGet", fn (MlirContext, Int16) -> MlirType
    ]()(ctx, bitwidth)


fn mlirIntegerTypeUnsignedGet(ctx: MlirContext, bitwidth: Int16) -> MlirType:
    """Creates an unsigned integer type of the given bitwidth in the context. The
    type is owned by the context."""
    return MLIR_func[
        "mlirIntegerTypeUnsignedGet", fn (MlirContext, Int16) -> MlirType
    ]()(ctx, bitwidth)


fn mlirIntegerTypeGetWidth(type: MlirType) -> Int16:
    """Returns the bitwidth of an integer type."""
    return MLIR_func["mlirIntegerTypeGetWidth", fn (MlirType) -> Int16]()(type)


fn mlirIntegerTypeIsSignless(type: MlirType) -> Bool:
    """Checks whether the given integer type is signless."""
    return MLIR_func["mlirIntegerTypeIsSignless", fn (MlirType) -> Bool]()(type)


fn mlirIntegerTypeIsSigned(type: MlirType) -> Bool:
    """Checks whether the given integer type is signed."""
    return MLIR_func["mlirIntegerTypeIsSigned", fn (MlirType) -> Bool]()(type)


fn mlirIntegerTypeIsUnsigned(type: MlirType) -> Bool:
    """Checks whether the given integer type is unsigned."""
    return MLIR_func["mlirIntegerTypeIsUnsigned", fn (MlirType) -> Bool]()(type)


# ===----------------------------------------------------------------------===//
#  Index type.
# ===----------------------------------------------------------------------===//


fn mlirIndexTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Index type."""
    return MLIR_func["mlirIndexTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAIndex(type: MlirType) -> Bool:
    """Checks whether the given type is an index type."""
    return MLIR_func["mlirTypeIsAIndex", fn (MlirType) -> Bool]()(type)


fn mlirIndexTypeGet(ctx: MlirContext) -> MlirType:
    """Creates an index type in the given context. The type is owned by the
    context."""
    return MLIR_func["mlirIndexTypeGet", fn (MlirContext) -> MlirType]()(ctx)


# ===----------------------------------------------------------------------===//
#  Floating-point types.
# ===----------------------------------------------------------------------===//


fn mlirFloat8E5M2TypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Float8E5M2 type."""
    return MLIR_func["mlirFloat8E5M2TypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAFloat8E5M2(type: MlirType) -> Bool:
    """Checks whether the given type is an f8E5M2 type."""
    return MLIR_func["mlirTypeIsAFloat8E5M2", fn (MlirType) -> Bool]()(type)


fn mlirFloat8E5M2TypeGet(ctx: MlirContext) -> MlirType:
    """Creates an f8E5M2 type in the given context. The type is owned by the
    context."""
    return MLIR_func["mlirFloat8E5M2TypeGet", fn (MlirContext) -> MlirType]()(
        ctx
    )


fn mlirFloat8E4M3FNTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Float8E4M3FN type."""
    return MLIR_func["mlirFloat8E4M3FNTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAFloat8E4M3FN(type: MlirType) -> Bool:
    """Checks whether the given type is an f8E4M3FN type."""
    return MLIR_func["mlirTypeIsAFloat8E4M3FN", fn (MlirType) -> Bool]()(type)


fn mlirFloat8E4M3FNTypeGet(ctx: MlirContext) -> MlirType:
    """Creates an f8E4M3FN type in the given context. The type is owned by the
    context."""
    return MLIR_func["mlirFloat8E4M3FNTypeGet", fn (MlirContext) -> MlirType]()(
        ctx
    )


fn mlirFloat8E5M2FNUZTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Float8E5M2FNUZ type."""
    return MLIR_func["mlirFloat8E5M2FNUZTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAFloat8E5M2FNUZ(type: MlirType) -> Bool:
    """Checks whether the given type is an f8E5M2FNUZ type."""
    return MLIR_func["mlirTypeIsAFloat8E5M2FNUZ", fn (MlirType) -> Bool]()(type)


fn mlirFloat8E5M2FNUZTypeGet(ctx: MlirContext) -> MlirType:
    """Creates an f8E5M2FNUZ type in the given context. The type is owned by the
    context."""
    return MLIR_func[
        "mlirFloat8E5M2FNUZTypeGet", fn (MlirContext) -> MlirType
    ]()(ctx)


fn mlirFloat8E4M3FNUZTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Float8E4M3FNUZ type."""
    return MLIR_func["mlirFloat8E4M3FNUZTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAFloat8E4M3FNUZ(type: MlirType) -> Bool:
    """Checks whether the given type is an f8E4M3FNUZ type."""
    return MLIR_func["mlirTypeIsAFloat8E4M3FNUZ", fn (MlirType) -> Bool]()(type)


fn mlirFloat8E4M3FNUZTypeGet(ctx: MlirContext) -> MlirType:
    """Creates an f8E4M3FNUZ type in the given context. The type is owned by the
    context."""
    return MLIR_func[
        "mlirFloat8E4M3FNUZTypeGet", fn (MlirContext) -> MlirType
    ]()(ctx)


fn mlirFloat8E4M3B11FNUZTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Float8E4M3B11FNUZ type."""
    return MLIR_func[
        "mlirFloat8E4M3B11FNUZTypeGetTypeID", fn () -> MlirTypeID
    ]()()


fn mlirTypeIsAFloat8E4M3B11FNUZ(type: MlirType) -> Bool:
    """Checks whether the given type is an f8E4M3B11FNUZ type."""
    return MLIR_func["mlirTypeIsAFloat8E4M3B11FNUZ", fn (MlirType) -> Bool]()(
        type
    )


fn mlirFloat8E4M3B11FNUZTypeGet(ctx: MlirContext) -> MlirType:
    """Creates an f8E4M3B11FNUZ type in the given context. The type is owned by the
    context."""
    return MLIR_func[
        "mlirFloat8E4M3B11FNUZTypeGet", fn (MlirContext) -> MlirType
    ]()(ctx)


fn mlirBFloat16TypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an BFloat16 type."""
    return MLIR_func["mlirBFloat16TypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsABF16(type: MlirType) -> Bool:
    """Checks whether the given type is a bf16 type."""
    return MLIR_func["mlirTypeIsABF16", fn (MlirType) -> Bool]()(type)


fn mlirBF16TypeGet(ctx: MlirContext) -> MlirType:
    """Creates a bf16 type in the given context. The type is owned by the
    context."""
    return MLIR_func["mlirBF16TypeGet", fn (MlirContext) -> MlirType]()(ctx)


fn mlirFloat16TypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Float16 type."""
    return MLIR_func["mlirFloat16TypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAF16(type: MlirType) -> Bool:
    """Checks whether the given type is an f16 type."""
    return MLIR_func["mlirTypeIsAF16", fn (MlirType) -> Bool]()(type)


fn mlirF16TypeGet(ctx: MlirContext) -> MlirType:
    """Creates an f16 type in the given context. The type is owned by the
    context."""
    return MLIR_func["mlirF16TypeGet", fn (MlirContext) -> MlirType]()(ctx)


fn mlirFloat32TypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Float32 type."""
    return MLIR_func["mlirFloat32TypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAF32(type: MlirType) -> Bool:
    """Checks whether the given type is an f32 type."""
    return MLIR_func["mlirTypeIsAF32", fn (MlirType) -> Bool]()(type)


fn mlirF32TypeGet(ctx: MlirContext) -> MlirType:
    """Creates an f32 type in the given context. The type is owned by the
    context."""
    return MLIR_func["mlirF32TypeGet", fn (MlirContext) -> MlirType]()(ctx)


fn mlirFloat64TypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Float64 type."""
    return MLIR_func["mlirFloat64TypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAF64(type: MlirType) -> Bool:
    """Checks whether the given type is an f64 type."""
    return MLIR_func["mlirTypeIsAF64", fn (MlirType) -> Bool]()(type)


fn mlirF64TypeGet(ctx: MlirContext) -> MlirType:
    """Creates a f64 type in the given context. The type is owned by the
    context."""
    return MLIR_func["mlirF64TypeGet", fn (MlirContext) -> MlirType]()(ctx)


fn mlirFloatTF32TypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of a TF32 type."""
    return MLIR_func["mlirFloatTF32TypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsATF32(type: MlirType) -> Bool:
    """Checks whether the given type is an TF32 type."""
    return MLIR_func["mlirTypeIsATF32", fn (MlirType) -> Bool]()(type)


fn mlirTF32TypeGet(ctx: MlirContext) -> MlirType:
    """Creates a TF32 type in the given context. The type is owned by the
    context."""
    return MLIR_func["mlirTF32TypeGet", fn (MlirContext) -> MlirType]()(ctx)


# ===----------------------------------------------------------------------===//
#  None type.
# ===----------------------------------------------------------------------===//


fn mlirNoneTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an None type."""
    return MLIR_func["mlirNoneTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsANone(type: MlirType) -> Bool:
    """Checks whether the given type is a None type."""
    return MLIR_func["mlirTypeIsANone", fn (MlirType) -> Bool]()(type)


fn mlirNoneTypeGet(ctx: MlirContext) -> MlirType:
    """Creates a None type in the given context. The type is owned by the
    context."""
    return MLIR_func["mlirNoneTypeGet", fn (MlirContext) -> MlirType]()(ctx)


# ===----------------------------------------------------------------------===//
#  Complex type.
# ===----------------------------------------------------------------------===//


fn mlirComplexTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Complex type."""
    return MLIR_func["mlirComplexTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAComplex(type: MlirType) -> Bool:
    """Checks whether the given type is a Complex type."""
    return MLIR_func["mlirTypeIsAComplex", fn (MlirType) -> Bool]()(type)


fn mlirComplexTypeGet(element_type: MlirType) -> MlirType:
    """Creates a complex type with the given element type in the same context as
    the element type. The type is owned by the context."""
    return MLIR_func["mlirComplexTypeGet", fn (MlirType) -> MlirType]()(
        element_type
    )


fn mlirComplexTypeGetElementType(type: MlirType) -> MlirType:
    """Returns the element type of the given complex type."""
    return MLIR_func[
        "mlirComplexTypeGetElementType", fn (MlirType) -> MlirType
    ]()(type)


# ===----------------------------------------------------------------------===//
#  Shaped type.
# ===----------------------------------------------------------------------===//


fn mlirTypeIsAShaped(type: MlirType) -> Bool:
    """Checks whether the given type is a Shaped type."""
    return MLIR_func["mlirTypeIsAShaped", fn (MlirType) -> Bool]()(type)


fn mlirShapedTypeGetElementType(type: MlirType) -> MlirType:
    """Returns the element type of the shaped type."""
    return MLIR_func[
        "mlirShapedTypeGetElementType", fn (MlirType) -> MlirType
    ]()(type)


fn mlirShapedTypeHasRank(type: MlirType) -> Bool:
    """Checks whether the given shaped type is ranked."""
    return MLIR_func["mlirShapedTypeHasRank", fn (MlirType) -> Bool]()(type)


fn mlirShapedTypeGetRank(type: MlirType) -> Int64:
    """Returns the rank of the given ranked shaped type."""
    return MLIR_func["mlirShapedTypeGetRank", fn (MlirType) -> Int64]()(type)


fn mlirShapedTypeHasStaticShape(type: MlirType) -> Bool:
    """Checks whether the given shaped type has a static shape."""
    return MLIR_func["mlirShapedTypeHasStaticShape", fn (MlirType) -> Bool]()(
        type
    )


fn mlirShapedTypeIsDynamicDim(type: MlirType, dim: Int) -> Bool:
    """Checks wither the dim-th dimension of the given shaped type is dynamic.
    """
    return MLIR_func[
        "mlirShapedTypeIsDynamicDim", fn (MlirType, Int) -> Bool
    ]()(type, dim)


fn mlirShapedTypeGetDimSize(type: MlirType, dim: Int) -> Int64:
    """Returns the dim-th dimension of the given ranked shaped type."""
    return MLIR_func["mlirShapedTypeGetDimSize", fn (MlirType, Int) -> Int64]()(
        type, dim
    )


fn mlirShapedTypeIsDynamicSize(size: Int64) -> Bool:
    """Checks whether the given value is used as a placeholder for dynamic sizes
    in shaped types."""
    return MLIR_func["mlirShapedTypeIsDynamicSize", fn (Int64) -> Bool]()(size)


fn mlirShapedTypeGetDynamicSize() -> Int64:
    """Returns the value indicating a dynamic size in a shaped type. Prefer
    mlirShapedTypeIsDynamicSize to direct comparisons with this value."""
    return MLIR_func["mlirShapedTypeGetDynamicSize", fn () -> Int64]()()


fn mlirShapedTypeIsDynamicStrideOrOffset(val: Int64) -> Bool:
    """Checks whether the given value is used as a placeholder for dynamic strides
    and offsets in shaped types."""
    return MLIR_func[
        "mlirShapedTypeIsDynamicStrideOrOffset", fn (Int64) -> Bool
    ]()(val)


fn mlirShapedTypeGetDynamicStrideOrOffset() -> Int64:
    """Returns the value indicating a dynamic stride or offset in a shaped type.
    Prefer mlirShapedTypeGetDynamicStrideOrOffset to direct comparisons with
    this value."""
    return MLIR_func[
        "mlirShapedTypeGetDynamicStrideOrOffset", fn () -> Int64
    ]()()


# ===----------------------------------------------------------------------===//
#  Vector type.
# ===----------------------------------------------------------------------===//


fn mlirVectorTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Vector type."""
    return MLIR_func["mlirVectorTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAVector(type: MlirType) -> Bool:
    """Checks whether the given type is a Vector type."""
    return MLIR_func["mlirTypeIsAVector", fn (MlirType) -> Bool]()(type)


fn mlirVectorTypeGet(
    rank: Int, shape: Pointer[Int64], element_type: MlirType
) -> MlirType:
    """Creates a vector type of the shape identified by its rank and dimensions,
    with the given element type in the same context as the element type. The
    type is owned by the context."""
    return MLIR_func[
        "mlirVectorTypeGet", fn (Int, Pointer[Int64], MlirType) -> MlirType
    ]()(rank, shape, element_type)


fn mlirVectorTypeGetChecked(
    loc: MlirLocation, rank: Int, shape: Pointer[Int64], element_type: MlirType
) -> MlirType:
    """Same as "mlirVectorTypeGet" but returns a nullptr wrapping MlirType on
    illegal arguments, emitting appropriate diagnostics."""
    return MLIR_func[
        "mlirVectorTypeGetChecked",
        fn (MlirLocation, Int, Pointer[Int64], MlirType) -> MlirType,
    ]()(loc, rank, shape, element_type)


fn mlirVectorTypeGetScalable(
    rank: Int,
    shape: Pointer[Int64],
    scalable: Pointer[Bool],
    element_type: MlirType,
) -> MlirType:
    """Creates a scalable vector type with the shape identified by its rank and
    dimensions. A subset of dimensions may be marked as scalable via the
    corresponding flag list, which is expected to have as many entries as the
    rank of the vector. The vector is created in the same context as the element
    type."""
    return MLIR_func[
        "mlirVectorTypeGetScalable",
        fn (Int, Pointer[Int64], Pointer[Bool], MlirType) -> MlirType,
    ]()(rank, shape, scalable, element_type)


fn mlirVectorTypeGetScalableChecked(
    loc: MlirLocation,
    rank: Int,
    shape: Pointer[Int64],
    scalable: Pointer[Bool],
    element_type: MlirType,
) -> MlirType:
    """Same as "mlirVectorTypeGetScalable" but returns a nullptr wrapping MlirType
    on illegal arguments, emitting appropriate diagnostics."""
    return MLIR_func[
        "mlirVectorTypeGetScalableChecked",
        fn (
            MlirLocation, Int, Pointer[Int64], Pointer[Bool], MlirType
        ) -> MlirType,
    ]()(loc, rank, shape, scalable, element_type)


fn mlirVectorTypeIsScalable(type: MlirType) -> Bool:
    """Checks whether the given vector type is scalable, i.e., has at least one
    scalable dimension."""
    return MLIR_func["mlirVectorTypeIsScalable", fn (MlirType) -> Bool]()(type)


fn mlirVectorTypeIsDimScalable(type: MlirType, dim: Int) -> Bool:
    """Checks whether the "dim"-th dimension of the given vector is scalable."""
    return MLIR_func[
        "mlirVectorTypeIsDimScalable", fn (MlirType, Int) -> Bool
    ]()(type, dim)


# ===----------------------------------------------------------------------===//
#  Ranked / Unranked Tensor type.
# ===----------------------------------------------------------------------===//


fn mlirTypeIsATensor(type: MlirType) -> Bool:
    """Checks whether the given type is a Tensor type."""
    return MLIR_func["mlirTypeIsATensor", fn (MlirType) -> Bool]()(type)


fn mlirRankedTensorTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an RankedTensor type."""
    return MLIR_func["mlirRankedTensorTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsARankedTensor(type: MlirType) -> Bool:
    """Checks whether the given type is a ranked tensor type."""
    return MLIR_func["mlirTypeIsARankedTensor", fn (MlirType) -> Bool]()(type)


fn mlirUnrankedTensorTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an UnrankedTensor type."""
    return MLIR_func["mlirUnrankedTensorTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAUnrankedTensor(type: MlirType) -> Bool:
    """Checks whether the given type is an unranked tensor type."""
    return MLIR_func["mlirTypeIsAUnrankedTensor", fn (MlirType) -> Bool]()(type)


fn mlirRankedTensorTypeGet(
    rank: Int,
    shape: Pointer[Int64],
    element_type: MlirType,
    encoding: MlirAttribute,
) -> MlirType:
    """Creates a tensor type of a fixed rank with the given shape, element type,
    and optional encoding in the same context as the element type. The type is
    owned by the context. Tensor types without any specific encoding field
    should assign mlirAttributeGetNull() to this parameter."""
    return MLIR_func[
        "mlirRankedTensorTypeGet",
        fn (Int, Pointer[Int64], MlirType, MlirAttribute) -> MlirType,
    ]()(rank, shape, element_type, encoding)


fn mlirRankedTensorTypeGetChecked(
    loc: MlirLocation,
    rank: Int,
    shape: Pointer[Int64],
    element_type: MlirType,
    encoding: MlirAttribute,
) -> MlirType:
    """Same as "mlirRankedTensorTypeGet" but returns a nullptr wrapping MlirType on
    illegal arguments, emitting appropriate diagnostics."""
    return MLIR_func[
        "mlirRankedTensorTypeGetChecked",
        fn (
            MlirLocation, Int, Pointer[Int64], MlirType, MlirAttribute
        ) -> MlirType,
    ]()(loc, rank, shape, element_type, encoding)


fn mlirRankedTensorTypeGetEncoding(type: MlirType) -> MlirAttribute:
    """Gets the 'encoding' attribute from the ranked tensor type, returning a null
    attribute if none."""
    return MLIR_func[
        "mlirRankedTensorTypeGetEncoding", fn (MlirType) -> MlirAttribute
    ]()(type)


fn mlirUnrankedTensorTypeGet(element_type: MlirType) -> MlirType:
    """Creates an unranked tensor type with the given element type in the same
    context as the element type. The type is owned by the context."""
    return MLIR_func["mlirUnrankedTensorTypeGet", fn (MlirType) -> MlirType]()(
        element_type
    )


fn mlirUnrankedTensorTypeGetChecked(
    loc: MlirLocation, element_type: MlirType
) -> MlirType:
    """Same as "mlirUnrankedTensorTypeGet" but returns a nullptr wrapping MlirType
    on illegal arguments, emitting appropriate diagnostics."""
    return MLIR_func[
        "mlirUnrankedTensorTypeGetChecked",
        fn (MlirLocation, MlirType) -> MlirType,
    ]()(loc, element_type)


# ===----------------------------------------------------------------------===//
#  Ranked / Unranked MemRef type.
# ===----------------------------------------------------------------------===//


fn mlirMemRefTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an MemRef type."""
    return MLIR_func["mlirMemRefTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAMemRef(type: MlirType) -> Bool:
    """Checks whether the given type is a MemRef type."""
    return MLIR_func["mlirTypeIsAMemRef", fn (MlirType) -> Bool]()(type)


fn mlirUnrankedMemRefTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an UnrankedMemRef type."""
    return MLIR_func["mlirUnrankedMemRefTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAUnrankedMemRef(type: MlirType) -> Bool:
    """Checks whether the given type is an UnrankedMemRef type."""
    return MLIR_func["mlirTypeIsAUnrankedMemRef", fn (MlirType) -> Bool]()(type)


fn mlirMemRefTypeGet(
    element_type: MlirType,
    rank: Int,
    shape: Pointer[Int64],
    layout: MlirAttribute,
    memory_space: MlirAttribute,
) -> MlirType:
    """Creates a MemRef type with the given rank and shape, a potentially empty
    list of affine layout maps, the given memory space and element type, in the
    same context as element type. The type is owned by the context."""
    return MLIR_func[
        "mlirMemRefTypeGet",
        fn (
            MlirType, Int, Pointer[Int64], MlirAttribute, MlirAttribute
        ) -> MlirType,
    ]()(element_type, rank, shape, layout, memory_space)


fn mlirMemRefTypeGetChecked(
    loc: MlirLocation,
    element_type: MlirType,
    rank: Int,
    shape: Pointer[Int64],
    layout: MlirAttribute,
    memory_space: MlirAttribute,
) -> MlirType:
    """Same as "mlirMemRefTypeGet" but returns a nullptr-wrapping MlirType o
    illegal arguments, emitting appropriate diagnostics."""
    return MLIR_func[
        "mlirMemRefTypeGetChecked",
        fn (
            MlirLocation,
            MlirType,
            Int,
            Pointer[Int64],
            MlirAttribute,
            MlirAttribute,
        ) -> MlirType,
    ]()(loc, element_type, rank, shape, layout, memory_space)


fn mlirMemRefTypeContiguousGet(
    element_type: MlirType,
    rank: Int,
    shape: Pointer[Int64],
    memory_space: MlirAttribute,
) -> MlirType:
    """Creates a MemRef type with the given rank, shape, memory space and element
    type in the same context as the element type. The type has no affine maps,
    i.e. represents a default row-major contiguous memref. The type is owned by
    the context."""
    return MLIR_func[
        "mlirMemRefTypeContiguousGet",
        fn (MlirType, Int, Pointer[Int64], MlirAttribute) -> MlirType,
    ]()(element_type, rank, shape, memory_space)


fn mlirMemRefTypeContiguousGetChecked(
    loc: MlirLocation,
    element_type: MlirType,
    rank: Int,
    shape: Pointer[Int64],
    memory_space: MlirAttribute,
) -> MlirType:
    """Same as "mlirMemRefTypeContiguousGet" but returns a nullptr wrapping
    MlirType on illegal arguments, emitting appropriate diagnostics."""
    return MLIR_func[
        "mlirMemRefTypeContiguousGetChecked",
        fn (
            MlirLocation, MlirType, Int, Pointer[Int64], MlirAttribute
        ) -> MlirType,
    ]()(loc, element_type, rank, shape, memory_space)


fn mlirUnrankedMemRefTypeGet(
    element_type: MlirType, memory_space: MlirAttribute
) -> MlirType:
    """Creates an Unranked MemRef type with the given element type and in the given
    memory space. The type is owned by the context of element type."""
    return MLIR_func[
        "mlirUnrankedMemRefTypeGet", fn (MlirType, MlirAttribute) -> MlirType
    ]()(element_type, memory_space)


fn mlirUnrankedMemRefTypeGetChecked(
    loc: MlirLocation, element_type: MlirType, memory_space: MlirAttribute
) -> MlirType:
    """Same as "mlirUnrankedMemRefTypeGet" but returns a nullptr wrapping
    MlirType on illegal arguments, emitting appropriate diagnostics."""
    return MLIR_func[
        "mlirUnrankedMemRefTypeGetChecked",
        fn (MlirLocation, MlirType, MlirAttribute) -> MlirType,
    ]()(loc, element_type, memory_space)


fn mlirMemRefTypeGetLayout(type: MlirType) -> MlirAttribute:
    """Returns the layout of the given MemRef type."""
    return MLIR_func[
        "mlirMemRefTypeGetLayout", fn (MlirType) -> MlirAttribute
    ]()(type)


fn mlirMemRefTypeGetAffineMap(type: MlirType) -> MlirAffineMap:
    """Returns the affine map of the given MemRef type."""
    return MLIR_func[
        "mlirMemRefTypeGetAffineMap", fn (MlirType) -> MlirAffineMap
    ]()(type)


fn mlirMemRefTypeGetMemorySpace(type: MlirType) -> MlirAttribute:
    """Returns the memory space of the given MemRef type."""
    return MLIR_func[
        "mlirMemRefTypeGetMemorySpace", fn (MlirType) -> MlirAttribute
    ]()(type)


fn mlirUnrankedMemrefGetMemorySpace(type: MlirType) -> MlirAttribute:
    """Returns the memory spcae of the given Unranked MemRef type."""
    return MLIR_func[
        "mlirUnrankedMemrefGetMemorySpace", fn (MlirType) -> MlirAttribute
    ]()(type)


# ===----------------------------------------------------------------------===//
#  Tuple type.
# ===----------------------------------------------------------------------===//


fn mlirTupleTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Tuple type."""
    return MLIR_func["mlirTupleTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsATuple(type: MlirType) -> Bool:
    """Checks whether the given type is a tuple type."""
    return MLIR_func["mlirTypeIsATuple", fn (MlirType) -> Bool]()(type)


fn mlirTupleTypeGet(
    ctx: MlirContext, num_elements: Int, elements: Pointer[MlirType]
) -> MlirType:
    """Creates a tuple type that consists of the given list of elemental types. The
    type is owned by the context."""
    return MLIR_func[
        "mlirTupleTypeGet", fn (MlirContext, Int, Pointer[MlirType]) -> MlirType
    ]()(ctx, num_elements, elements)


fn mlirTupleTypeGetNumTypes(type: MlirType) -> Int:
    """Returns the number of types contained in a tuple."""
    return MLIR_func["mlirTupleTypeGetNumTypes", fn (MlirType) -> Int]()(type)


fn mlirTupleTypeGetType(type: MlirType, pos: Int) -> MlirType:
    """Returns the pos-th type in the tuple type."""
    return MLIR_func["mlirTupleTypeGetType", fn (MlirType, Int) -> MlirType]()(
        type, pos
    )


# ===----------------------------------------------------------------------===//
#  Function type.
# ===----------------------------------------------------------------------===//


fn mlirFunctionTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Function type."""
    return MLIR_func["mlirFunctionTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAFunction(type: MlirType) -> Bool:
    """Checks whether the given type is a function type."""
    return MLIR_func["mlirTypeIsAFunction", fn (MlirType) -> Bool]()(type)


fn mlirFunctionTypeGet(
    ctx: MlirContext,
    num_inputs: Int,
    inputs: Pointer[MlirType],
    num_results: Int,
    results: Pointer[MlirType],
) -> MlirType:
    """Creates a function type, mapping a list of input types to result types.
    """
    return MLIR_func[
        "mlirFunctionTypeGet",
        fn (
            MlirContext, Int, Pointer[MlirType], Int, Pointer[MlirType]
        ) -> MlirType,
    ]()(ctx, num_inputs, inputs, num_results, results)


fn mlirFunctionTypeGetNumInputs(type: MlirType) -> Int:
    """Returns the number of input types."""
    return MLIR_func["mlirFunctionTypeGetNumInputs", fn (MlirType) -> Int]()(
        type
    )


fn mlirFunctionTypeGetNumResults(type: MlirType) -> Int:
    """Returns the number of result types."""
    return MLIR_func["mlirFunctionTypeGetNumResults", fn (MlirType) -> Int]()(
        type
    )


fn mlirFunctionTypeGetInput(type: MlirType, pos: Int) -> MlirType:
    """Returns the pos-th input type."""
    return MLIR_func[
        "mlirFunctionTypeGetInput", fn (MlirType, Int) -> MlirType
    ]()(type, pos)


fn mlirFunctionTypeGetResult(type: MlirType, pos: Int) -> MlirType:
    """Returns the pos-th result type."""
    return MLIR_func[
        "mlirFunctionTypeGetResult", fn (MlirType, Int) -> MlirType
    ]()(type, pos)


# ===----------------------------------------------------------------------===//
#  Opaque type.
# ===----------------------------------------------------------------------===//


fn mlirOpaqueTypeGetTypeID() -> MlirTypeID:
    """Returns the typeID of an Opaque type."""
    return MLIR_func["mlirOpaqueTypeGetTypeID", fn () -> MlirTypeID]()()


fn mlirTypeIsAOpaque(type: MlirType) -> Bool:
    """Checks whether the given type is an opaque type."""
    return MLIR_func["mlirTypeIsAOpaque", fn (MlirType) -> Bool]()(type)


fn mlirOpaqueTypeGet(
    ctx: MlirContext, dialect_namespace: MlirStringRef, type_data: MlirStringRef
) -> MlirType:
    """Creates an opaque type in the given context associated with the dialect
    identified by its namespace. The type contains opaque byte data of the
    specified length (data need not be null-terminated)."""
    return MLIR_func[
        "mlirOpaqueTypeGet",
        fn (MlirContext, MlirStringRef, MlirStringRef) -> MlirType,
    ]()(ctx, dialect_namespace, type_data)


fn mlirOpaqueTypeGetDialectNamespace(type: MlirType) -> MlirStringRef:
    """Returns the namespace of the dialect with which the given opaque type
    is associated. The namespace string is owned by the context."""
    return MLIR_func[
        "mlirOpaqueTypeGetDialectNamespace", fn (MlirType) -> MlirStringRef
    ]()(type)


fn mlirOpaqueTypeGetData(type: MlirType) -> MlirStringRef:
    """Returns the raw data as a string reference. The data remains live as long as
    the context in which the type lives."""
    return MLIR_func["mlirOpaqueTypeGetData", fn (MlirType) -> MlirStringRef]()(
        type
    )
