# ===----------------------------------------------------------------------=== #
# Copyright (c) 2025, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

"""Standardized response object for Pipeline Inference."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from max.interfaces import GenerationStatus


@dataclass
class EmbeddingsResponse:
    """Container for the response from embeddings pipeline."""

    embeddings: np.ndarray


class AudioGenerationResponse:
    def __init__(
        self,
        final_status: GenerationStatus,
        audio: np.ndarray | None = None,
        buffer_speech_tokens: np.ndarray | None = None,
    ) -> None:
        self._audio = audio
        self._final_status = final_status
        self._buffer_speech_tokens = buffer_speech_tokens

    @property
    def is_done(self) -> bool:
        return self._final_status.is_done

    @property
    def has_audio_data(self) -> bool:
        return self._audio is not None

    @property
    def audio_data(self) -> np.ndarray:
        assert self._audio is not None
        return self._audio

    @property
    def final_status(self) -> GenerationStatus:
        return self._final_status

    @property
    def buffer_speech_tokens(self) -> np.ndarray | None:
        """An optional field potentially containing the last N speech tokens
        generated by the model. This is used to buffer speech tokens for
        a followup request."""
        return self._buffer_speech_tokens
