# ===----------------------------------------------------------------------=== #
# Copyright (c) 2025, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #
# RUN: %mojo-no-debug %s | FileCheck %s

from buffer import DimList
from internal_utils import TestTensor, assert_equal
from nn.gather_scatter import scatter_nd_generator


fn test_case[
    type: DType,
](
    data: TestTensor[type, 3],
    indices: TestTensor[DType.int64, 2],
    updates: TestTensor[type, 3],
    output: TestTensor[type, 3],
) raises:
    @always_inline
    @parameter
    fn use_update[
        _type: DType, width: Int
    ](input_val: SIMD[_type, width], update_val: SIMD[_type, width]) -> SIMD[
        _type, width
    ]:
        return update_val

    test_case[type, use_update](data, indices, updates, output)


fn test_case[
    type: DType,
    reduce_fn: fn[type: DType, width: Int] (
        SIMD[type, width], SIMD[type, width]
    ) capturing [_] -> SIMD[type, width],
](
    data: TestTensor[type, 3],
    indices: TestTensor[DType.int64, 2],
    updates: TestTensor[type, 3],
    output: TestTensor[type, 3],
) raises:
    var output_ref = output

    # Note: This is for the specific set of examples
    #      (due to _to_ndbuffer[] parameters).
    # last example 3,2,2,3 ; original: 3,2,3,3
    scatter_nd_generator[
        type, DType.int64, 3, 2, 3, False, reduce_fn=reduce_fn
    ](
        data.ndbuffer,
        indices.ndbuffer,
        updates.ndbuffer,
        output.ndbuffer,
    )

    assert_equal(output, output_ref)


fn main() raises:
    fn test_scatternd() raises:
        print("== test_scatternd")
        var data = TestTensor[DType.float32, 3](
            DimList(4, 4, 4),
            List[Float32](
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
            ),
        )

        var indices = TestTensor[DType.int64, 2](
            DimList(2, 1), List[Int64](0, 2)
        )

        var updates = TestTensor[DType.float32, 3](
            DimList(2, 4, 4),
            List[Float32](
                5,
                5,
                5,
                5,
                6,
                6,
                6,
                6,
                7,
                7,
                7,
                7,
                8,
                8,
                8,
                8,
                1,
                1,
                1,
                1,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                3,
                4,
                4,
                4,
                4,
            ),
        )

        var output_ref = TestTensor[DType.float32, 3](
            DimList(4, 4, 4),
            List[Float32](
                5,
                5,
                5,
                5,
                6,
                6,
                6,
                6,
                7,
                7,
                7,
                7,
                8,
                8,
                8,
                8,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                1,
                1,
                1,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                3,
                4,
                4,
                4,
                4,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
            ),
        )

        test_case[DType.float32](
            data,
            indices,
            updates,
            output_ref,
        )

    # CHECK-LABEL: test_scatternd
    # CHECK-NOT: FAIL
    test_scatternd()

    fn test_scatternd_add() raises:
        print("== test_scatternd_add")
        var data = TestTensor[DType.float32, 3](
            DimList(4, 4, 4),
            List[Float32](
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
            ),
        )

        var indices = TestTensor[DType.int64, 2](
            DimList(2, 1), List[Int64](0, 0)
        )

        var updates = TestTensor[DType.float32, 3](
            DimList(2, 4, 4),
            List[Float32](
                5,
                5,
                5,
                5,
                6,
                6,
                6,
                6,
                7,
                7,
                7,
                7,
                8,
                8,
                8,
                8,
                1,
                1,
                1,
                1,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                3,
                4,
                4,
                4,
                4,
            ),
        )

        var output_ref = TestTensor[DType.float32, 3](
            DimList(4, 4, 4),
            List[Float32](
                7,
                8,
                9,
                10,
                13,
                14,
                15,
                16,
                18,
                17,
                16,
                15,
                16,
                15,
                14,
                13,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
            ),
        )

        @always_inline
        @parameter
        fn _add[
            ty: DType, width: Int
        ](v1: SIMD[ty, width], v2: SIMD[ty, width]) -> SIMD[ty, width]:
            return v1 + v2

        test_case[DType.float32, _add](data, indices, updates, output_ref)

    # CHECK-LABEL: test_scatternd_add
    # CHECK-NOT: FAIL
    test_scatternd_add()

    fn test_scatternd_max() raises:
        print("== test_scatternd_max")
        var data = TestTensor[DType.float32, 3](
            DimList(4, 4, 4),
            List[Float32](
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
            ),
        )

        var indices = TestTensor[DType.int64, 2](
            DimList(2, 1), List[Int64](0, 0)
        )

        var updates = TestTensor[DType.float32, 3](
            DimList(2, 4, 4),
            List[Float32](
                5,
                5,
                5,
                5,
                6,
                6,
                6,
                6,
                7,
                7,
                7,
                7,
                8,
                8,
                8,
                8,
                1,
                1,
                1,
                1,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                3,
                4,
                4,
                4,
                4,
            ),
        )

        var output_ref = TestTensor[DType.float32, 3](
            DimList(4, 4, 4),
            List[Float32](
                5,
                5,
                5,
                5,
                6,
                6,
                7,
                8,
                8,
                7,
                7,
                7,
                8,
                8,
                8,
                8,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
            ),
        )

        @always_inline
        @parameter
        fn _max[
            ty: DType, width: Int
        ](v1: SIMD[ty, width], v2: SIMD[ty, width]) -> SIMD[ty, width]:
            return max(v1, v2)

        test_case[DType.float32, _max](data, indices, updates, output_ref)

    # CHECK-LABEL: test_scatternd_max
    # CHECK-NOT: FAIL
    test_scatternd_max()

    fn test_scatternd_min() raises:
        print("== test_scatternd_min")
        var data = TestTensor[DType.float32, 3](
            DimList(4, 4, 4),
            List[Float32](
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
            ),
        )

        var indices = TestTensor[DType.int64, 2](
            DimList(2, 1), List[Int64](0, 0)
        )

        var updates = TestTensor[DType.float32, 3](
            DimList(2, 4, 4),
            List[Float32](
                5,
                5,
                5,
                5,
                6,
                6,
                6,
                6,
                7,
                7,
                7,
                7,
                8,
                8,
                8,
                8,
                1,
                1,
                1,
                1,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                3,
                4,
                4,
                4,
                4,
            ),
        )

        var output_ref = TestTensor[DType.float32, 3](
            DimList(4, 4, 4),
            List[Float32](
                1,
                1,
                1,
                1,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                3,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
            ),
        )

        @always_inline
        @parameter
        fn _min[
            ty: DType, width: Int
        ](v1: SIMD[ty, width], v2: SIMD[ty, width]) -> SIMD[ty, width]:
            return min(v1, v2)

        test_case[DType.float32, _min](data, indices, updates, output_ref)

    # CHECK-LABEL: test_scatternd_min
    # CHECK-NOT: FAIL
    test_scatternd_min()

    fn test_scatternd_multiply() raises:
        print("== test_scatternd_multiply")
        var data = TestTensor[DType.float32, 3](
            DimList(4, 4, 4),
            List[Float32](
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
            ),
        )

        var indices = TestTensor[DType.int64, 2](
            DimList(2, 1), List[Int64](0, 0)
        )

        var updates = TestTensor[DType.float32, 3](
            DimList(2, 4, 4),
            List[Float32](
                5,
                5,
                5,
                5,
                6,
                6,
                6,
                6,
                7,
                7,
                7,
                7,
                8,
                8,
                8,
                8,
                1,
                1,
                1,
                1,
                2,
                2,
                2,
                2,
                3,
                3,
                3,
                3,
                4,
                4,
                4,
                4,
            ),
        )

        var output_ref = TestTensor[DType.float32, 3](
            DimList(4, 4, 4),
            List[Float32](
                5,
                10,
                15,
                20,
                60,
                72,
                84,
                96,
                168,
                147,
                126,
                105,
                128,
                96,
                64,
                32,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                8,
                7,
                6,
                5,
                4,
                3,
                2,
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
            ),
        )

        @always_inline
        @parameter
        fn _mul[
            ty: DType, width: Int
        ](v1: SIMD[ty, width], v2: SIMD[ty, width]) -> SIMD[ty, width]:
            return v1 * v2

        test_case[DType.float32, _mul](data, indices, updates, output_ref)

    # CHECK-LABEL: test_scatternd_multiply
    # CHECK-NOT: FAIL
    test_scatternd_multiply()
